### ISSUE TITLE
Please help run the app and learn from it for your valuable project. I tried 2-3 days.

### ISSUE THREAD

**Issue by arafat1971** [ailtoncunhasilva/Flutter-project-multi-store#1]
![Screenshot_2020-10-15-20-43-48-006_com example delivery_morenope 1](https://user-images.githubusercontent.com/25308963/96147672-593a4980-0f29-11eb-9c4d-072b9563d15d.jpg)
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════ The method '[]' was called on null. Receiver: null Tried calling: []("status") The relevant error-causing widget was:    StreamBuilder<DocumentSnapshot> file:///H:/Logos/Flutter-project-multi-store-master/lib/tiles/stores_tile.dart:97:12 ════════════════════════════════════════════════════════════════════════════════════════════════════  ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════ The method '[]' was called on null. Receiver: null Tried calling: []("status") The relevant error-causing widget was:    StreamBuilder<DocumentSnapshot> file:///H:/Logos/Flutter-project-multi-store-master/lib/tiles/stores_tile.dart:8:12 ════════════════════════════════════════════════════════════════════════════════════════════════════  ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════ The method '[]' was called on null. Receiver: null Tried calling: []("status") The relevant error-causing widget was:   
 StreamBuilder<DocumentSnapshot> file:///H:/Logos/Flutter-project-multi-store-master/lib/tiles/stores_tile.dart:52:12  

 Here is the path folder code

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:delivery_morenope/tabs/stores_tab.dart';
import 'package:flutter/material.dart';

class ApalhocaTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(    **Android studio indicate here is the problem** **very classes make this error.**
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja01')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StorePalhocaTab()));
                            },
                      child: _buildItens(context, 'images/lojaA.jpg',
                          'Restaurante e Pizzaria', 'O Palhoção')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class DeliciaTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja02')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                    onTap: snapshot.data['status'] == false
                        ? null
                        : () {
                            Navigator.of(context).push(MaterialPageRoute(
                                builder: (context) => StoreDeliciaTab()));
                          },
                    child: _buildItens(context, 'images/lojaB.jpg',
                        'Restaurante e Pizzaria', 'Pizzaria Deliciosa'),
                  ),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class OboticarioTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja03')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreBoticarioTab()));
                            },
                      child: _buildItens(context, 'images/lojaC.jpg',
                          'Perfumaria', 'O Boticário')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class MinhaCoxinhaFavoritaTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja04')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) =>
                                      StoreMinhaCoxinhaFavoritaTab()));
                            },
                      child: _buildItens(context, 'images/lojaD.jpg',
                          'Lanchonete', 'Minha\nEmpada Favorita')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class MagoEspetionhoTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja05')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) =>
                                      StoreMagoEspetinhoTab()));
                            },
                      child: _buildItens(context, 'images/lojaE.jpg',
                          'Espetinho', 'Magão do Espetinho')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class DaLenaTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja06')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreDalenaTab()));
                            },
                      child: _buildItens(context, 'images/lojaF.jpg',
                          'Hamburgueria', 'Helena\nHamburgueria')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class DindinTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja07')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreDindinTab()));
                            },
                      child: _buildItens(context, 'images/lojaG.jpg',
                          'Lanchonete', 'Gourmet')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class PizzaMaitaTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja09')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StorePizzaMaitaTab()));
                            },
                      child: _buildItens(context, 'images/lojaI.jpg',
                          'Pizzaria Delivery', 'Pizza Oxente')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LeChefTile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja08')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLeChefTab()));
                            },
                      child: _buildItens(
                          context, 'images/lojaH.jpg', 'Pizzaria', 'Chef')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LojaJ extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja10')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLojaJTab()));
                            },
                      child: _buildItens(context, 'images/lojaJ.jpg', 'Doceria',
                          'Sabores Delícia')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LojaL extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja11')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLojaLTab()));
                            },
                      child: _buildItens(context, 'images/lojaL.jpg',
                          'Farmácia', 'Pague Pouco')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LojaM extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja12')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLojaMTab()));
                            },
                      child: _buildItens(context, 'images/lojaM.jpg', 'Padaria',
                          'Sabores do Pão')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LojaN extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja13')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {}
          return Column(
            children: <Widget>[
              Padding(
                padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                child: InkWell(
                    onTap: snapshot.data['status'] == false
                        ? null
                        : () {
                            Navigator.of(context).push(MaterialPageRoute(
                                builder: (context) => StoreLojaNTab()));
                          },
                    child: _buildItens(context, 'images/lojaN.jpg', 'Armazém',
                        'João Ferragens')),
              ),
              Text(
                snapshot.data['status'] == true
                    ? 'Estabelecimento ABERTO'
                    : 'Estabelecimento FECHADO',
                style: TextStyle(
                    color: snapshot.data['status'] == true
                        ? Colors.greenAccent[700]
                        : Colors.red),
              )
            ],
          );
        });
  }
}

class LojaO extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja14')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLojaOTab()));
                            },
                      child: _buildItens(context, 'images/lojaO.jpg', 'Bar',
                          'Tô Perto de Casa')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

class LojaP extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('statusStore')
            .document('statusLoja15')
            .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(
              child: CircularProgressIndicator(),
            );
          } else {
            return Column(
              children: <Widget>[
                Padding(
                  padding: EdgeInsets.only(left: 10, top: 4, right: 10),
                  child: InkWell(
                      onTap: snapshot.data['status'] == false
                          ? null
                          : () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) => StoreLojaPTab()));
                            },
                      child: _buildItens(context, 'images/lojaP.jpg',
                          'Papelaria', 'Happylândia')),
                ),
                Text(
                  snapshot.data['status'] == true
                      ? 'Estabelecimento ABERTO'
                      : 'Estabelecimento FECHADO',
                  style: TextStyle(
                      color: snapshot.data['status'] == true
                          ? Colors.greenAccent[700]
                          : Colors.red),
                )
              ],
            );
          }
        });
  }
}

Widget _buildItens(context, imgStore, preName, storeName) {
  return //Card(
      //margin: EdgeInsets.symmetric(horizontal: 2, vertical: 1),
      //elevation: 1,
      /*child:*/ Padding(
          padding: EdgeInsets.all(4),
          child: Container(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Container(
                    child: Row(children: [
                  Container(
                    height: 70,
                    width: 70,
                    decoration: BoxDecoration(
                      image: DecorationImage(image: AssetImage(imgStore)),
                      border: Border.all(
                          color: Colors.grey[400],
                          style: BorderStyle.solid,
                          width: 1),
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                  SizedBox(width: 10),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(preName,
                          style:
                              TextStyle(fontSize: 14, color: Colors.grey[600])),
                      Text(
                        storeName,
                        style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Colors.grey[800]),
                      ),
                    ],
                  ),
                ])),
                //Icon(Icons.store, color: Colors.grey[500], size: 18),
              ],
            ),
          )); //);
}

**Comment by ailtoncunhasilva** [comment]
My project use Firebase on the back end. Did you configure the Firebase? I see the "status" return null. It´s necessary to configure the project with Firebase.

**Comment by arafat1971** [comment]
This is my firebase backend. create account is working but after show page error 
![SharedScreenshot11](https://user-images.githubusercontent.com/25308963/96337895-22407100-10ac-11eb-9933-7c9406a589c8.jpg)
![SharedScreenshot9](https://user-images.githubusercontent.com/25308963/96337897-24a2cb00-10ac-11eb-8af0-c7a6247298df.jpg)
![SharedScreenshot8](https://user-images.githubusercontent.com/25308963/96337898-253b6180-10ac-11eb-873d-09f21a9e5b15.jpg)
![SharedScreenshot7](https://user-images.githubusercontent.com/25308963/96337899-266c8e80-10ac-11eb-9e26-fa92d1701048.jpg)
![SharedScreenshot6](https://user-images.githubusercontent.com/25308963/96337901-279dbb80-10ac-11eb-8c99-4a550aab49e5.jpg)
![SharedScreenshot5](https://user-images.githubusercontent.com/25308963/96337902-28cee880-10ac-11eb-8ffc-c13baefc2bbd.jpg)0
![SharedScreenshot4](https://user-images.githubusercontent.com/25308963/96337904-2a98ac00-10ac-11eb-8469-9a8beef0f92c.jpg)
![SharedScreenshot3](https://user-images.githubusercontent.com/25308963/96337907-2f5d6000-10ac-11eb-94ff-a5182aacb9e1.jpg)
![2sc](https://user-images.githubusercontent.com/25308963/96337909-308e8d00-10ac-11eb-8032-18592abb8a06.jpg)
![t](https://user-images.githubusercontent.com/25308963/96337910-31bfba00-10ac-11eb-928d-56ab909db74b.jpg)

**Comment by arafat1971** [comment]
I have a sturtup i want to sart my business with your code, i have no more money to bye a project and developer, my business at 2019. If you have time you can help me, sir.

**Comment by ailtoncunhasilva** [comment]
I can help you, but i can´t to work free... I´m sorry...

**Comment by arafat1971** [comment]
Thank you .

**Comment by ailtoncunhasilva** [comment]
I'm sorry

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
